/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ng2-fone.module';
import * as import2 from './ng2-fone';
class Ng2FoneModuleInjector extends import0.ɵNgModuleInjector<import1.Ng2FoneModule> {
  _Ng2FoneModule_0:import1.Ng2FoneModule;
  __Ng2Fone_1:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Ng2Fone_1():any {
    if ((this.__Ng2Fone_1 == null)) { (this.__Ng2Fone_1 = import1.Ng2FoneFactory()); }
    return this.__Ng2Fone_1;
  }
  createInternal():import1.Ng2FoneModule {
    this._Ng2FoneModule_0 = new import1.Ng2FoneModule();
    return this._Ng2FoneModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2FoneModule)) { return this._Ng2FoneModule_0; }
    if ((token === import2.Ng2Fone)) { return this._Ng2Fone_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2FoneModuleNgFactory:import0.NgModuleFactory<import1.Ng2FoneModule> = new import0.NgModuleFactory<any>(Ng2FoneModuleInjector,import1.Ng2FoneModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovYW5ndWxhcjIvbmctZm9uZS9zcmMvbmcyLWZvbmUubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2FuZ3VsYXIyL25nLWZvbmUvc3JjL25nMi1mb25lLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
